import type { Metadata } from "next"
import { LegalLayout } from "../../lib/legal-layout"

export const metadata: Metadata = { title: "Terms of Service – Supplement Snap" }

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="mb-3 text-base font-semibold text-zinc-900">{title}</h2>
      {children}
    </section>
  )
}

export default function TermsPage() {
  return (
    <LegalLayout title="Terms of Service">
      <Section title="Introduction">
        <p>Welcome to Supplement Snap. By accessing or using our platform, you agree to be bound by these Terms of Service. If you do not agree, please do not use the service.</p>
      </Section>

      <Section title="Description of Service">
        <p>Supplement Snap provides cloud-based software that helps roofing contractors document concealed roof damage discovered during tear-off, generate professional insurance supplement documentation, export PDF reports, and send reports to insurance adjusters via email.</p>
      </Section>

      <Section title="User Responsibilities">
        <p>You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to provide accurate and complete information when creating your account and using the service.</p>
        <p className="mt-2">You are responsible for ensuring that the content you upload, including photos and field notes, is accurate and does not violate any applicable laws or regulations.</p>
      </Section>

      <Section title="Acceptable Use">
        <p>You may not use Supplement Snap to:</p>
        <ul className="mt-2 list-disc pl-5 space-y-1">
          <li>Submit fraudulent or misleading insurance documentation</li>
          <li>Upload content that violates third-party rights</li>
          <li>Attempt to gain unauthorized access to other accounts or systems</li>
          <li>Use the platform for any illegal purpose</li>
          <li>Resell or redistribute the service without authorization</li>
        </ul>
      </Section>

      <Section title="Subscription and Billing">
        <p>Supplement Snap offers a Starter Plan that includes a one-time setup fee and a recurring monthly subscription. Payment is processed through Stripe. By subscribing, you authorize us to charge the payment method on file for the applicable fees.</p>
        <p className="mt-2">Your subscription will automatically renew each billing cycle unless canceled. You may manage your subscription and payment methods through your account dashboard or the Stripe billing portal.</p>
      </Section>

      <Section title="Cancellation">
        <p>You may cancel your subscription at any time through the billing portal. Upon cancellation, your access to premium features will remain active until the end of the current billing period. No partial refunds will be issued for the remaining days in a billing cycle.</p>
      </Section>

      <Section title="Limitation of Liability">
        <p>Supplement Snap is provided &quot;as is&quot; without warranties of any kind. We do not guarantee that the service will be uninterrupted, error-free, or secure. We are not responsible for the accuracy of supplement documentation generated by the platform or for the outcome of any insurance claim submissions.</p>
        <p className="mt-2">To the maximum extent permitted by law, Supplement Snap and its affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the service.</p>
      </Section>

      <Section title="Changes to Terms">
        <p>We reserve the right to modify these terms at any time. Changes will be posted on this page with an updated date. Continued use of the service after changes constitutes acceptance of the revised terms.</p>
      </Section>

      <Section title="Contact">
        <p>If you have questions about these terms, contact us at <span className="font-medium text-zinc-900">support@supplementsnap.com</span>.</p>
      </Section>
    </LegalLayout>
  )
}
